In [70]:
import numpy as np 

In [71]:
arr = np.random.randint(0, 100, (4,3))
print(arr)
print()
print(np.sort(arr))
print()
print(arr[arr[:, 1].argsort()])
print()
print(np.array(sorted(arr, key = lambda x: max(x))))
print()
print(np.sort(arr, axis = None).reshape(4,3))

[[21 25 77]
 [71 75 89]
 [18  5 38]
 [45 39 90]]

[[21 25 77]
 [71 75 89]
 [ 5 18 38]
 [39 45 90]]

[[18  5 38]
 [21 25 77]
 [45 39 90]
 [71 75 89]]

[[18  5 38]
 [21 25 77]
 [71 75 89]
 [45 39 90]]

[[ 5 18 21]
 [25 38 39]
 [45 71 75]
 [77 89 90]]


In [72]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
# Add marks every student of an extra subject in the same array.
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
marks = np.concatenate([marks, extra_subject], axis = 1)
# Add two new students marks in respective 5 subjects.
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1, -1)
rec2 = np.array( [92, 71, 52, 61, 53]).reshape(1, -1)
marks = np.concatenate([marks, rec1, rec2], axis = 0)
# Add extra column with sum of all subjects
sum_of_stud = marks.sum(axis = 1, keepdims=True)
marks = np.concatenate([marks, sum_of_stud], axis = 1)
# Sort the array(non-ascending order) on total marks column
print(np.array(sorted(marks, key = lambda x: x[-1], reverse=True)))

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]


In [73]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
print(np.unique(arr, axis = 0))
print()
print(np.unique(arr, axis = 1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


In [74]:
arr = np.array([[1,2,3,3,1,1],
               [0,9,1,2,8,8],
               [1,2,3,8,8,8],
               [1,2,3,3,1,1],
               [0,6,1,2,11,7],
               [10,19,14,-2,8,-1]])
np.flip(arr, axis = [0, 1])

array([[-1,  8, -2, 14, 19, 10],
       [ 7, 11,  2,  1,  6,  0],
       [ 1,  1,  3,  3,  2,  1],
       [ 8,  8,  8,  3,  2,  1],
       [ 8,  8,  2,  1,  9,  0],
       [ 1,  1,  3,  3,  2,  1]])

In [75]:
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] )
X = 6

np.where(np.any(arr > X, axis = 1))

(array([1, 3], dtype=int64),)

In [76]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,11)

In [77]:
np.concatenate([arr1,arr2,arr3])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
max_element = arr.argmax()
min_element = arr.argmin()
print(arr.max(), arr.min())
arr = np.delete(arr, max_element, axis = 1)
arr = np.delete(arr, min_element, axis = 1)
print(arr.max(), arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998 103
997 117
