In [37]:
import numpy as np

In [38]:
a=np.nan*np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [39]:
a,b = map(int, input("Enter two numbers: ").split())
x=np.random.random((a,b))
print(x)
print(x.mean())

[[0.39242413 0.17273867 0.5652656  0.47869695 0.46504153]
 [0.44744853 0.91430145 0.7235208  0.23086972 0.10146445]]
0.4491771825693457


In [40]:
def borderArray(a,b):
    x=np.ones((a,b))
    x[1:-1,1:-1]=0
    return x
borderArray(5,5)    

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [42]:
np.eye(4)
np.identity(4) #both method will show same results

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [67]:
a=np.random.randint(1,100,(10,2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([111,  99,  45, 116, 122, 108, 116,  87,  75, 103])

In [70]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [74]:
a = np.array([])
a = np.array([1, 2])
a = np.zeros((3,3))
a.size

9

In [121]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)
a = np.arange(10).reshape(2,-1)
print("a =",a)
b = np.repeat(1, 10).reshape(2,-1)
print("b =",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
c = np.round(c,2)
print("c =", c)
vertical_stack(a,b,c)

a = [[0 1 2 3 4]
 [5 6 7 8 9]]
b = [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c = [[0.12 0.04 0.22 0.81 0.08]
 [0.8  0.9  0.39 0.58 0.8 ]]


array([[0.  , 1.  , 2.  , 3.  , 4.  ],
       [5.  , 6.  , 7.  , 8.  , 9.  ],
       [1.  , 1.  , 1.  , 1.  , 1.  ],
       [1.  , 1.  , 1.  , 1.  , 1.  ],
       [0.12, 0.04, 0.22, 0.81, 0.08],
       [0.8 , 0.9 , 0.39, 0.58, 0.8 ]])

In [77]:
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

array([6., 5., 4.], dtype=float32)

In [124]:
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30,
        "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}
    end = end.split("-")
    end_last = int(end[-1]) + 1    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2025-03-26', end = '2025-04-2')

array(['2025-03-26', '2025-03-27', '2025-03-28', '2025-03-29',
       '2025-03-30', '2025-03-31', '2025-04-01', '2025-04-02'],
      dtype='datetime64[D]')

In [125]:
x = np.random.random((5,4))
x - x.mean(axis = 1, keepdims = True)

array([[-0.22400613,  0.36016905, -0.12523528, -0.01092763],
       [ 0.50438707, -0.03369223, -0.02470236, -0.44599247],
       [ 0.28644128,  0.0674094 , -0.11709278, -0.2367579 ],
       [-0.04306771, -0.20008586, -0.02414884,  0.26730241],
       [-0.12785858,  0.28350622, -0.15331333, -0.00233431]])

In [ ]:
a = np.arange(9).reshape(3,3)
a[:, [0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [132]:
a = np.arange(10)
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [133]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,4,7,2])
a[b>a] = b[a<b]
a

array([6, 3, 4, 7, 8])

In [134]:
def nthmax(arr, n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

34

In [135]:
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])