### Advance Numpy

In [260]:
# Code
import numpy as np
a = np.random.randint(1,100,15)
a

array([52, 82, 60, 38,  5,  8, 28, 10, 50, 34, 25, 60, 55, 93,  5])

In [261]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[58, 71, 47, 61],
       [46, 53, 48, 38],
       [21, 59, 82, 49],
       [21, 97, 18, 68],
       [36, 30, 12, 96],
       [61, 65, 51, 99]])

In [262]:
np.sort(a)

array([ 5,  5,  8, 10, 25, 28, 34, 38, 50, 52, 55, 60, 60, 82, 93])

In [263]:
np.sort(b,axis=0)[::-1]

array([[61, 97, 82, 99],
       [58, 71, 51, 96],
       [46, 65, 48, 68],
       [36, 59, 47, 61],
       [21, 53, 18, 49],
       [21, 30, 12, 38]])

In [264]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[58., 71., 47., 61.,  1.],
       [46., 53., 48., 38.,  1.],
       [21., 59., 82., 49.,  1.],
       [21., 97., 18., 68.,  1.],
       [36., 30., 12., 96.,  1.],
       [61., 65., 51., 99.,  1.]])

In [265]:
a.shape

(15,)

In [266]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [267]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [268]:
# np.where
np.where(a>50)

(array([ 0,  1,  2, 11, 12, 13], dtype=int64),)

In [269]:
# np.where(condition,true,false)
np.where(a>50,1,0)

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [270]:
# np.argmax
np.argmax(a)

13

In [271]:
# np.cumsum
np.cumsum(b,axis=1)

array([[ 58, 129, 176, 237],
       [ 46,  99, 147, 185],
       [ 21,  80, 162, 211],
       [ 21, 118, 136, 204],
       [ 36,  66,  78, 174],
       [ 61, 126, 177, 276]])

In [272]:
#np.cumprod
np.cumprod(b,axis=0)

array([[         58,          71,          47,          61],
       [       2668,        3763,        2256,        2318],
       [      56028,      222017,      184992,      113582],
       [    1176588,    21535649,     3329856,     7723576],
       [   42357168,   646069470,    39958272,   741463296],
       [-1711180048,  -955157410,  2037871872,   390422272]])

In [273]:
np.percentile(b,50,axis=1)

array([59.5, 47. , 54. , 44.5, 33. , 63. ])

In [274]:
np.histogram(b,bins=[10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 3, 4, 4, 4, 1, 1, 3], dtype=int64),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [275]:
np.clip(a,a_min=5,a_max=95)

array([52, 82, 60, 38,  5,  8, 28, 10, 50, 34, 25, 60, 55, 93,  5])