In [56]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [57]:
X,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [58]:
df=pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [59]:
df.head()

feature1  feature2      target
0  1.773628  1.148900  173.261156
1  0.965047 -1.645799 -105.466255
2 -1.297395 -0.870573  -78.152911
3  1.751509 -0.694508   83.540484
4 -0.195562  1.167619   47.562633

In [60]:
fig = px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [62]:
from sklearn.linear_model import LinearRegression

In [63]:
lr = LinearRegression()

In [64]:
lr.fit(X_train,y_train)

LinearRegression()

In [65]:
y_pred = lr.predict(X_test)

In [66]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 37.726150799397786
MSE 1958.6640750445906
R2 score 0.8205748530207329


In [67]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)
z = z_final

In [68]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.add_trace(go.Surface(x = x, y = y, z =z ))
fig.show()

In [69]:
lr.coef_

array([34.10972198, 80.73966768])

In [70]:
lr.intercept_

11.08246305465442

### Code from Scratch

In [71]:
import numpy as np
from sklearn.datasets import load_diabetes

In [72]:
X,y = load_diabetes(return_X_y=True)

In [73]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [74]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [75]:
X.shape

(442, 10)

In [76]:
y.shape

(442,)

#### Using Sklearn's Linear Regression

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
X_train,y_train,X_test,y_test=train_test_split(X,y,test_size=0.2,random_state=3)

In [79]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(353,)


In [80]:
from sklearn.linear_model import LinearRegression

In [81]:
reg=LinearRegression()

In [83]:
reg.fit(X_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [353, 89]