#### Numpy array v/s Python lists

In [59]:
# Speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []

import time 
start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

1.1161177158355713


In [60]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.09301137924194336


In [61]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)/1024/1024

84.96776580810547

In [62]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)/1024/1024

9.536849975585938

#### Advance Indexing

In [63]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# Fancy Indexing
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [65]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[12, 31, 24, 81],
       [81, 66, 14, 86],
       [12, 66, 25, 64],
       [69,  7, 45, 67],
       [43, 40, 68, 61],
       [92, 98, 77, 63]])

In [66]:
# find all numbers greater than 50
a[a > 50]

array([81, 81, 66, 86, 66, 64, 69, 67, 68, 61, 92, 98, 77, 63])

In [67]:
# find out even numbers
a[a % 2 == 0]

array([12, 24, 66, 14, 86, 12, 66, 64, 40, 68, 92, 98])

In [68]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([66, 86, 66, 64, 68, 92, 98])

#### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [69]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [70]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [71]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [72]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a)
print(b)
print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [73]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)
print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [74]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


a = np.arange(20)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999])

In [75]:
# mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [76]:
def mse(actual,predicted):
  return np.mean((actual - predicted)**2)
mse(actual,predicted)

386.68