### Advance Numpy

In [1]:
# Code
import numpy as np
a = np.random.randint(1,100,15)
a

array([99, 35, 51, 85, 90, 66, 42, 99, 26, 58, 71, 97, 33, 16,  7])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[33, 13, 80, 18],
       [77, 25, 72, 28],
       [ 3, 28, 79, 86],
       [ 2, 39, 70, 13],
       [16, 59, 93, 53],
       [87, 33, 64, 45]])

In [3]:
np.sort(a)

array([ 7, 16, 26, 33, 35, 42, 51, 58, 66, 71, 85, 90, 97, 99, 99])

In [4]:
np.sort(b,axis=0)[::-1]

array([[87, 59, 93, 86],
       [77, 39, 80, 53],
       [33, 33, 79, 45],
       [16, 28, 72, 28],
       [ 3, 25, 70, 18],
       [ 2, 13, 64, 13]])

In [5]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[33., 13., 80., 18.,  1.],
       [77., 25., 72., 28.,  1.],
       [ 3., 28., 79., 86.,  1.],
       [ 2., 39., 70., 13.,  1.],
       [16., 59., 93., 53.,  1.],
       [87., 33., 64., 45.,  1.]])

In [6]:
a.shape

(15,)

In [7]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [8]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [9]:
# np.where
np.where(a>50)

(array([ 0,  2,  3,  4,  5,  7,  9, 10, 11], dtype=int64),)

In [10]:
# np.where(condition,true,false)
np.where(a>50,1,0)

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [11]:
# np.argmax
np.argmax(a)

0

In [12]:
# np.cumsum
np.cumsum(b,axis=1)

array([[ 33,  46, 126, 144],
       [ 77, 102, 174, 202],
       [  3,  31, 110, 196],
       [  2,  41, 111, 124],
       [ 16,  75, 168, 221],
       [ 87, 120, 184, 229]])

In [13]:
#np.cumprod
np.cumprod(b,axis=0)

array([[         33,          13,          80,          18],
       [       2541,         325,        5760,         504],
       [       7623,        9100,      455040,       43344],
       [      15246,      354900,    31852800,      563472],
       [     243936,    20939100, -1332656896,    29864016],
       [   21222432,   690990300,   609304576,  1343880720]])

In [14]:
np.percentile(b,50,axis=1)

array([25.5, 50. , 53.5, 26. , 56. , 54.5])

In [15]:
np.histogram(b,bins=[10,20,30,40,50,60,70,80,90,100])

(array([4, 3, 3, 1, 2, 1, 4, 3, 1], dtype=int64),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [16]:
np.clip(a,a_min=5,a_max=95)

array([95, 35, 51, 85, 90, 66, 42, 95, 26, 58, 71, 95, 33, 16,  7])