#### Numpy

In [12]:
import numpy as np

In [13]:
my_arr=np.arange(15).reshape(3,5)
print('Before:- ')
print(my_arr)

def swap(arr,start_index,end_index):
    arr[:,[start_index,end_index]]=arr[:,[end_index,start_index]]
swap(my_arr,1,3)    
print('After:- ')
print(my_arr)    

Before:- 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
After:- 
[[ 0  3  2  1  4]
 [ 5  8  7  6  9]
 [10 13 12 11 14]]


In [14]:
my_arr=np.arange(5*5).reshape(5,5)
print(my_arr.shape)
arr_5d=my_arr[np.newaxis,np.newaxis,...,np.newaxis,np.newaxis]
arr_5d.shape

(5, 5)


(1, 1, 5, 5, 1, 1)

In [15]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
my_arr=np.hstack((arr1,arr2))
my_arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [16]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
my_arr=np.vstack((arr1,arr2))
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7.2,8,9],[10,11.3,12]])
my_arr=np.concatenate((arr1,arr2),axis=1)
my_arr

array([[ 1. ,  2. ,  3. ,  7.2,  8. ,  9. ],
       [ 4. ,  5. ,  6. , 10. , 11.3, 12. ]])

In [18]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
my_arr0=np.stack((arr1,arr2),axis=0)
my_arr1=np.stack((arr1,arr2),axis=1)
my_arr2=np.stack((arr1,arr2),axis=2)
print(my_arr0)
print(my_arr1)
print(my_arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [19]:
# import numpy 
import numpy as np 

gfg1 = np.array([[10], [2], [13]]) 
gfg2 = np.array([[41], [55], [6]]) 

# using numpy.dstack() method 
print(np.dstack((gfg1, gfg2))) 
print()
print(np.stack((gfg1, gfg2)))


[[[10 41]]

 [[ 2 55]]

 [[13  6]]]

[[[10]
  [ 2]
  [13]]

 [[41]
  [55]
  [ 6]]]


In [20]:
import numpy as np
# Creating an example array
array = np.arange(6)
# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 3,axis=0)
print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)


Array:
[0 1 2 3 4 5]

Result after numpy.split():
[array([0, 1]), array([2, 3]), array([4, 5])]


In [21]:
import numpy as np
my_arr = np.arange(24).reshape((2, 3, 4))
result = np.dsplit(my_arr, 2)
print("Original 3D Array:")
print(my_arr)
print("\nResult after numpy.dsplit():")
print(result)

Original 3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Result after numpy.dsplit():
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [22]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
print("Array a :", a)
print("Array b :", b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))


Array a : [101  99  87]
Array b : [897  97 111]
a > b
[False  True False]
a >= b
[False  True False]
a < b
[ True False  True]
a <= b
[ True False  True]
